### ISSUE TITLE
[Epic] Data Explorer product roadmap

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-explorer#24]
Moved from gitlab, originally created by @starsinmypockets 

TODO - Fill out ticket, this is a stub

# Analysis

Some notes from a discussion with @Irio and @starsinmypockets (Edited for clarity / concision)

Paul Walker
8:29 AM
Feel free to ping me if you have questions. I am concerned about the backward compatability issue / maintanance overhead of maintaining multiple versions of the data explorer...
We released it quickly so I know there are stability issue. It would be ideal if additional development to address stability and improve performance, add features, could be shared with a roadmap for the explorer that all the existing projects could benefit from.

Irio Musskopf
8:31 AM
Something I was about to ask was on project reviews. If Datopian has them, it would be a good moment to try to produce these project integrations.

Paul Walker
8:32 AM
I agree 100%.

Irio Musskopf
8:32 AM
Such as asking "What and how can we reuse what was developed for Axenit in future projects? How much extra effort, right now, is required to do so?"

[...]

Paul Walker
8:35 AM
My guess is that there needs to be analysis around [how to extend] tools [for use in client projects] like - frontend-v2 has a plugin and a theme structure that make it easy to extend / override for project requirements.
Data explorer in theory could fit this model. Some sort of plugin architecture.
And a stable core 🖤

Irio Musskopf
8:36 AM
"shared with a roadmap for the explorer that all the existing projects could benefit from."

I'd say this would make an excellent list key-actions while being easy to estimate effort and cost.

Paul Walker
8:37 AM
Yes, I agree.
🙂

Paul Walker
8:40 AM
At the least we should be semantic versioning so we know what releases break backwards compatibility

Irio Musskopf
8:41 AM
Axenit is scheduled to end in about 3 weeks. I'd propose to set a reminder for this date so we can return to this topic and give it more time for discussion. Maybe an open video meeting to gather ideas, define a plan, and later negotiate possibilities with management. What do you think about that?

Paul Walker
8:42 AM
Sounds great. If you think the technology (data explorer) has a future. I do think it's a useful framework and a roadmap would be helpful.

Irio Musskopf
8:43 AM
By "define a plan," I mean putting in words the main arguments why we want to work on these things and, in a high level, define what "these things" are.

Paul Walker
8:43 AM
Yes. I think the main thing is to capture these points in an issue or document.

Paul Walker
8:46 AM
I'll create an epic for data explorer roadmap in ckan next gen board and copy/paste some of the notes from here

**Comment by anuveyatsu** [comment]
*Comment from Rufus:*

> Note: like quite a few things in "Next Gen" I feel they are more usefully thought of as a "framework" aka "pattern + libraries" rather than a "product". I.e. they are not something you take off the shelf and tweak a few variables. It's more like a framework which you use to build your solution. Think of flask as a framework vs e.g. squarespace. Of course, some things are a mix like wordpress: for simple users its a product. For advanced users its a framework.

**Comment by rufuspollock** [comment]
OBSOLETE.
