### ISSUE TITLE
How to create new builds that contain updated components?

### ISSUE THREAD

**Issue by EvgeniiaVak** [datopian/data-explorer#28]
I need a new build with updated `datastore-query-builder`, which for now is in the separate branch - https://github.com/datopian/datastore-query-builder/tree/eds-feature/toggle-copy-uri.

I edited this line in data explorer dependencies (to use the `datastore-query-builder` from the feature branch)
```
"@datopian/datastore-query-builder": "https://github.com/datopian/datastore-query-builder.git#eds-feature/toggle-copy-uri"
```

You can see code in this data-explorer branch - https://github.com/datopian/data-explorer/tree/eds-feature/custom-copy-api-url

This worked and now if I `yarn install` and go to `node_modules` I see my new code. But when I build (`yarn build`) it's not in the build. Do I miss a step somewhere?

@anuveyatsu

**Comment by sagargg** [comment]
@EvgeniiaVak Have you tried removing  `yarn.lock` then reinstalling and build.

**Comment by anuveyatsu** [comment]
@EvgeniiaVak the steps would be:

1) Prepare `datastore-query-builder` with dist version (eg run `yarn build:package`)
2) Install from a git branch using package manager (don't do it manually) so it updates `yarn.lock` file: `yarn add https://github.com/datopian/datastore-query-builder.git#eds-feature/toggle-copy-uri`
3) You can verify the installed code by diffing `yarn.lock` - you would expect to see your latest commit id there.
4) Run `yarn build`

**Comment by EvgeniiaVak** [comment]
thanks @anuveyatsu! I'll also prep a PR adding this info to the docs here https://tech.datopian.com/data-explorer/#new-builds

**Comment by EvgeniiaVak** [comment]
FIXED. See https://github.com/datopian/tech.datopian.com/pull/21

**Comment by EvgeniiaVak** [comment]
When updating a component (e.g. `datastore-query-builder`) - **do not run `yarn upgrade <component>`** it will cause different versions of react-dom

E.g. these are versions currently in master brach
```
evgeniyavakarina (master) data-explorer-master $  npm ls react-dom
@datopian/data-explorer@0.4.13 /Users/evgeniyavakarina/Documents/GitHub/data-explorer-master
├─┬ @datopian/chart-builder@0.1.4
│ └── react-dom@16.12.0  deduped
├─┬ @datopian/datapackage-views-js@1.3.15
│ └── react-dom@16.12.0  deduped
├─┬ @datopian/datastore-query-builder@0.4.11
│ └── react-dom@16.12.0  deduped
├─┬ @datopian/map-builder@0.1.7
│ └── react-dom@16.12.0  deduped
└── react-dom@16.12.0 
```

These are versions in EDS branch
```
@datopian/data-explorer@0.4.13 /Users/evgeniyavakarina/Documents/GitHub/data-explorer
├─┬ @datopian/chart-builder@0.1.4
│ └── react-dom@16.12.0  deduped
├─┬ @datopian/datapackage-views-js@1.3.15 invalid
│ └── react-dom@16.12.0  deduped
├─┬ @datopian/datastore-query-builder@0.4.10 invalid
│ └── react-dom@16.12.0  deduped
├─┬ @datopian/map-builder@0.1.7
│ └── react-dom@16.12.0  deduped
└── react-dom@16.12.0 

npm ERR! invalid: @datopian/datapackage-views-js@1.3.15 /Users/evgeniyavakarina/Documents/GitHub/data-explorer/node_modules/@datopian/datapackage-views-js
npm ERR! invalid: @datopian/datastore-query-builder@0.4.10 /Users/evgeniyavakarina/Documents/GitHub/data-explorer/node_modules/@datopian/datastore-query-builder
```
(the invalid errors do not cause the issue)

and these are after running `yarn upgrade @datopian/datastore-query-builder` which causes [invalid hook error](https://reactjs.org/warnings/invalid-hook-call-warning.html):
```
@datopian/data-explorer@0.4.13 /Users/evgeniyavakarina/Documents/GitHub/data-explorer
├─┬ @datopian/chart-builder@0.1.4
│ └── react-dom@16.12.0 
├─┬ @datopian/datapackage-views-js@1.3.15 invalid
│ └── react-dom@16.13.1  deduped
├─┬ @datopian/attic /datastore-query-builder@0.4.10 invalid
│ └── react-dom@16.13.1  deduped
├─┬ @datopian/map-builder@0.1.7
│ └── react-dom@16.12.0 
└── react-dom@16.13.1 

npm ERR! invalid: @datopian/datapackage-views-js@1.3.15 /Users/evgeniyavakarina/Documents/GitHub/data-explorer/node_modules/@datopian/datapackage-views-js
npm ERR! invalid: @datopian/datastore-query-builder@0.4.10 /Users/evgeniyavakarina/Documents/GitHub/data-explorer/node_modules/@datopian/datastore-query-builder
```
